// This code is generated by GitHub Copilot (VS Code)

/**
 * Navigation script for WordWizards vocabulary app
 * Handles navigation between different pages through the iframe
 */

// Function to navigate to different pages
function navigate(page) {
    const contentFrame = document.getElementById('contentFrame');
    const navItems = document.querySelectorAll('.nav-item');
    
    // Update the iframe source
    contentFrame.src = `pages/${page}.html`;
    
    // Update active navigation item
    navItems.forEach(item => {
        const icon = item.querySelector('i');
        const text = item.querySelector('span');
        
        if (item.querySelector('span').textContent.toLowerCase() === page) {
            icon.className = icon.className.replace('text-gray-500', 'text-blue-500');
            text.className = text.className.replace('text-gray-500', 'text-blue-500');
        } else {
            icon.className = icon.className.replace('text-blue-500', 'text-gray-500');
            text.className = text.className.replace('text-blue-500', 'text-gray-500');
        }
    });
}

// Function to navigate to parent dashboard (unlocked for direct access)
function navigateToParent() {
    // Direct access to parent dashboard without PIN verification
    document.getElementById('contentFrame').src = "pages/parent.html";
}
