# This code is generated by GitHub Copilot (VS Code)
import requests
from typing import Any, Dict, List


def get_copilot_activity(org: str, token: str) -> Dict[str, Any]:
    """
    Query GitHub Copilot activity for users in an organization.
    
    Args:
        org: GitHub organization name
        token: Personal access token with required scopes: OAuth app tokens 
               and personal access tokens (classic) need either the 
               manage_billing:copilot or read:org scopes to use this endpoint.
    
    Returns:
        JSON response as a dictionary
    """
    url = f"https://api.github.com/orgs/{org}/copilot/billing/seats"
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28"
    }
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return response.json()

def extract_user_activity_info(data: Dict[str, Any]) -> List[Dict[str, str]]:
    """
    Extract key information for each user from Copilot activity data.
    
    Args:
        data: Copilot activity data retrieved from GitHub API
        
    Returns:
        List of dictionaries containing user key information, each dictionary contains:
        - username: Username
        - last_activity_at: Last activity timestamp
        - last_activity_editor: Last used editor
    """
    user_info_list = []
    
    seats = data.get("seats", [])
    for seat in seats:
        assignee = seat.get("assignee", {})
        username = assignee.get("login", "N/A")
        last_activity_at = seat.get("last_activity_at", "N/A")
        last_activity_editor = seat.get("last_activity_editor", "N/A")
        
        user_info = {
            "username": username,
            "last_activity_at": last_activity_at,
            "last_activity_editor": last_activity_editor
        }
        user_info_list.append(user_info)
    
    return user_info_list


def print_user_activity_summary(data: Dict[str, Any]) -> None:
    """
    Print user activity summary information.
    
    Args:
        data: Copilot activity data retrieved from GitHub API
    """
    print("=" * 80)
    print("GitHub Copilot User Activity Summary")
    print("=" * 80)
    
    total_seats = data.get("total_seats", 0)
    print(f"Total users: {total_seats}")
    print()
    
    user_info_list = extract_user_activity_info(data)
    
    for i, user_info in enumerate(user_info_list, 1):
        print(f"User {i}:")
        print(f"  Username: {user_info['username']}")
        print(f"  Last activity at: {user_info['last_activity_at']}")
        print(f"  Last activity editor: {user_info['last_activity_editor']}")
        print()

if __name__ == "__main__":
    # Example usage:
    # Replace 'ORG', 'YOUR-TOKEN' with actual values
    org = 'your-organization'
    token = 'your-github-token'
    
    try:
        data = get_copilot_activity(org, token)
        
        # Print user activity summary
        print_user_activity_summary(data)
        
        # Uncomment the line below if you need raw data
        # print("Raw data:", data)
        
    except requests.exceptions.RequestException as e:
        print(f"API request failed: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")