# This code is generated by GitHub Copilot (VS Code)

import requests

# This code is generated by GitHub Copilot (VS Code)
def get_enterprise_users(enterprise_name, token):
    """
    Retrieves a list of users for a given enterprise.

    Args:
        enterprise_name (str): The name of the enterprise.
        token (str): The personal access token for authentication.

    Returns:
        requests.Response: The response object from the API call.
    """
    url = f"https://api.github.com/scim/v2/enterprises/{enterprise_name}/Users"
    headers = {
        "Accept": "application/scim+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28"
    }
    response = requests.get(url, headers=headers)
    return response

def add_enterprise_team_member(enterprise, team, username, token):
    """
    Adds a user to an enterprise team.

    Args:
        enterprise (str): The name of the enterprise.
        team (str): The name of the team.
        username (str): The username of the user to add.
        token (str): The personal access token for authentication.

    Returns:
        requests.Response: The response object from the API call.
    """
    url = f"https://api.github.com/enterprises/{enterprise}/teams/{team}/memberships/{username}"
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28"
    }
    response = requests.put(url, headers=headers)
    return response